version: 2

multi-ecosystem-groups:
  quarterly-dependencies:
    schedule:
      interval: "quarterly"
    assignees:
      - "vowstar"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "quarterly-dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "quarterly-dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
